import type { NextPage } from 'next';
import Head from 'next/head';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import NavBar from '../components/NavBar';
import Projects from '../components/Projects';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wilson Goltara</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <Hero />
      <Projects />
      <Contact />
    </>
  );
};

export default Home;
